### ISSUE TITLE
Not working with own API key

### ISSUE THREAD

**Issue by Thorazin** [penguin-teal/gnome-openweather#53] opened 2024-06-28 21:11 UTC
## Description

I have my own account and API key on weatherapi . com and I am still not getting a weather forecast or current conditions as of today, June 28th 2024.

Describe the bug.

As stated above, I am not getting any data even though I am using my own API key and am not over the limit of 1 million calls per month on the free plan.

## System

# System Details Report
---

## Report details
- **Date generated:**                              2024-06-28 16:10:15

## Hardware Information:
- **Hardware Model:**                              ASUS ProArt X670E-CREATOR WIFI
- **Memory:**                                      64.0 GiB
- **Processor:**                                   AMD Ryzen™ 9 7950X × 32
- **Graphics:**                                    Radeon™ RX 7900 XTX
- **Disk Capacity:**                               6.0 TB

## Software Information:
- **Firmware Version:**                            2007
- **OS Name:**                                     Ubuntu 24.04 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.0-36-generic

Which Linux distro are you using?

Ubuntu 24.04 

## Settings

```json
Go to extension settings > "About" > "Copy Settings JSON" and paste here.
```
{"app-version":"137","git-version":"137.r0.g2bf2d07","gnome-version":"46.0","user-locale":"en","unit":"'fahrenheit'","custom-keys":["","<REDACTED>",""],"appid":"<REDACTED>","actual-city":"0","weather-provider":"'weatherapicom'","has-run":"true","refresh-interval-current":"1800","decimal-places":"1","locs":[{}],"weatherapidotcom-key":"<REDACTED>","geolocation-appid-mapquest":"<REDACTED>","pressure-unit":"'inHg'","refresh-interval-forecast":"14400","loc-refresh-interval":"120.0","position-in-panel":"'center'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}

**Comment by Ticklezz** [comment] 2024-06-28 21:12
Yeah seems my own API isn't working either.

**Comment by Thorazin** [comment] 2024-06-28 21:13
Bummer. Any idea what can be done about it? This is my favorite extension.

**Comment by Ticklezz** [comment] 2024-06-28 21:15
> Bummer. Any idea what can be done about it? This is my favorite extension.

No clue as my own API was working till just now.

**Comment by Ticklezz** [comment] 2024-06-28 21:25
It looks like we have an update.

**Comment by furkansimsekli** [comment] 2024-06-28 21:25
I can confirm that my api doesn't work either. It's from https://weatherapi.com. And I use v137 on Ubuntu 24.04. Users with no api can't access any weather info either, it throws "too many requests" error just like it did at #35

**Comment by Ticklezz** [comment] 2024-06-28 21:26
> I can confirm that my api doesn't work either. It's from https://weatherapi.com. And I use v137 on Ubuntu 24.04. Users with no api can't access any weather info either, it throws "too many requests" error just like it did at #35

Did you update the extension?

**Comment by Thorazin** [comment] 2024-06-28 21:27
I did update the extension, and restarterd my computer, reentered the api key, etc...

**Comment by derek-shnosh** [comment] 2024-06-28 21:28
I just notice this as well, but noticed this time I'm getting a more generic message about WeatherAPI.com having too many users and to try switching weather providers. As opposed to previous messages regarding API limits.

**Comment by Ticklezz** [comment] 2024-06-28 21:28
> I did update the extension, and restarterd my computer, reentered the api key, etc...

Did it take your API key? I logged out and it took my key but not loading. It might take a minute as it did before.

**Comment by Thorazin** [comment] 2024-06-28 21:29
> > I did update the extension, and restarterd my computer, reentered the api key, etc...
> 
> Did it take your API key? I logged out and it took my key but not loading. It might take a minute as it did before.

It appears that it did but it's been at least a half hour and still not working.

**Comment by Ticklezz** [comment] 2024-06-28 21:38
> > > I did update the extension, and restarterd my computer, reentered the api key, etc...
> > 
> > 
> > Did it take your API key? I logged out and it took my key but not loading. It might take a minute as it did before.
> 
> It appears that it did but it's been at least a half hour and still not working.

Well that sucks.

**Comment by mikemolina** [comment] 2024-06-28 22:28
Hi!
I also confirm same bug in my system (Ubuntu 24.04) after update the extension, with my api key from [https://openweathermap.org](https://openweathermap.org) Output generated with button 'Copy settings JSON':
> {"app-version":"137",
"git-version":"137.r0.g2bf2d07",
"gnome-version":"46.0",
"user-locale":"es",
"custom-keys":["<REDACTED>","",""],
"appid":"<REDACTED>",
"actual-city":"0",
"weather-provider":"'openweathermap'",
"hi-contrast":"'white'",
"has-run":"true",
"refresh-interval-current":"1200",
"delay-ext-init":"5",
"locs":[{}],
"center-forecast":"true",
"owm-api-translate":"true",
"expand-forecast":"false",
"pressure-decimal-places":"-1",
"show-sunsetrise-in-panel":"false",
"last-init-error":"'(2024/05/12) TypeError: settings.set_value is not a function'",
"my-loc-prov":"'ipinfoio'",
"weatherapidotcom-key":"<REDACTED>",
"show-comment-in-forecast":"true",
"use-system-icons":"true",
"wind-direction":"false",
"geolocation-appid-mapquest":"<REDACTED>",
"refresh-interval-forecast":"5400",
"loc-refresh-interval":"90.0",
"menu-alignment":"64.772727272727266",
"show-comment-in-panel":"false"}
>
Is a good extension!!

**Comment by johnpiers** [comment] 2024-06-29 00:12
I've got 2 API keys from OpenWeatherMap. On my PC it eventually stuck and the extension's been working fine with zero notifications. On my laptop the key stays put but bugger all works and spams me with notifications. Both machines are Arch installs with Gnome and both extensions are the latest. v137. Not sure how helpful my comment is but  perhaps is may be useful.  😊

**Comment by TheRealWolfick** [comment] 2024-06-29 00:50
My weatherAPI key still isn't working. When I close the settings tab, the changes aren't saved and the customapi toggle is reset as off when I open it again. Is it just not saving/updating?

**Comment by robatino** [comment] 2024-06-29 00:59
> My weatherAPI key still isn't working. When I close the settings tab, the changes aren't saved and the customapi toggle is reset as off when I open it again. Is it just not saving/updating?

I noticed this as well. With OpenWeatherMap and Visual Crossing, I can save the personal API key, and there's a square with a check mark to the left of the API key. With WeatherAPI.com, if I enter the personal API key, it only shows a triangle with an exclamation mark next to the API key. If I switch to a different provider and then back, the WeatherAPI.com API key is gone.

In addition, after logging out and back in, I briefly had a weather forecast, but after making some changes I don't get one anymore. Haven't tried logging out/in again.

**Comment by TheRealWolfick** [comment] 2024-06-29 01:12
So I have a temporary solution to anyone stuck or can't get the API key to stick. You can replace the default key in the top of the getweather.js file (WeatherAPI is the second one), then log out and in or otherwise reload your gnome session.

**Comment by TheRealWolfick** [comment] 2024-06-29 01:21
Looking through the XML file, it appears that custom keys are deprecated for WeatherAPI and OpenWeather? Also, there is a a typo in one of the names "use-default-owm-key".

![image](https://github.com/penguin-teal/gnome-openweather/assets/128224725/4bef172e-f165-4235-9a1e-a733989de146)

**Comment by Ticklezz** [comment] 2024-06-29 01:39
> So I have a temporary solution to anyone stuck or can't get the API key to stick. You can replace the default key in the top of the getweather.js file (WeatherAPI is the second one) with your personal API key, then log out and in or otherwise reload your gnome session.
> 
> (You could possibly just manually add it into the second field of the custom-keys array in the schemas/*.xml file as well) *untested

Nice workaround.

**Comment by Thorazin** [comment] 2024-06-29 01:49
It appears as if my api key is bewing saved between loads and after restarts, etc... this is what it looks like for me, with key blocked out of course.

![Screenshot from 2024-06-28 20-46-59-obfuscated](https://github.com/penguin-teal/gnome-openweather/assets/36058075/8b1deb44-2c00-4303-8ce8-faad64df24db)

**Comment by Thorazin** [comment] 2024-06-29 01:50
> > My weatherAPI key still isn't working. When I close the settings tab, the changes aren't saved and the customapi toggle is reset as off when I open it again. Is it just not saving/updating?
> 
> I noticed this as well. With OpenWeatherMap and Visual Crossing, I can save the personal API key, and there's a square with a check mark to the left of the API key. With WeatherAPI.com, if I enter the personal API key, it only shows a triangle with an exclamation mark next to the API key. If I switch to a different provider and then back, the WeatherAPI.com API key is gone.
> 
> In addition, after logging out and back in, I briefly had a weather forecast, but after making some changes I don't get one anymore. Haven't tried logging out/in again.
> 
> Edit: Actually, it looks like I got the WeatherAPI.com API key to stick, but it still shows a triangle with an exclamation point, unlike the other two providers. What do the symbols to the left of the API key indicate?


Where can I find this file to modify?

**Comment by furkansimsekli** [comment] 2024-06-29 02:19
> Where can I find this file to modify?

try `~/.local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/getweather.js`

**Comment by Thorazin** [comment] 2024-06-29 02:51
> > Where can I find this file to modify?
> 
> try `~/.local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/getweather.js`


Thanks.

**Comment by mikemolina** [comment] 2024-06-29 03:53
> So I have a temporary solution to anyone stuck or can't get the API key to stick. You can replace the default key in the top of the getweather.js file (WeatherAPI is the second one) with your personal API key, then log out and in or otherwise reload your gnome session.
> 
> (You could possibly just manually add it into the second field of the custom-keys array in the schemas/*.xml file as well) *untested

Thanks for the solution!!
I confirm normal functioning of the extension. In my case, I modified the line with `DEFAULT_KEYS` in the file _getweather.js_ for my **OpenWeather API key**. Here a patch:

```sh
--- .local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/getweather.js~	2024-06-28 10:34:51.000000000 -0500
+++ .local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/getweather.js	2024-06-28 20:57:29.150809455 -0500
@@ -22,7 +22,7 @@
 
 export const DEFAULT_KEYS =
 [
-  "b4d6a638dd4af5e668ccd8574fd90cec",
+  "<My OPENWEATHERMAP api-key>",
   "7a4baea97ef946c7864221259240804",
   "ES25QFD3CP93EZ9DMSJ72MAX7"
 ];
```

The second key it allow to change **Weather API key** and third for **Visual Crossing API** key.
The image show settings of the extension.
![Settings](https://github.com/penguin-teal/gnome-openweather/assets/8185531/99b1619f-01e1-4efd-8609-fad9a2c0af31)

**Comment by creeper82** [comment] 2024-06-29 13:19
Same thing. Manually setting the api key in JS file is somewhat good but lasts until update obviously. What I find weird is that the yesterday's update was literally made to fix custom API key problems, and yet it still doesn't work :P

**Comment by furkansimsekli** [comment] 2024-06-29 13:41
> What I find weird is that the yesterday's update was literally made to fix custom API key problems, and yet it still doesn't work :P

It was a fix for this getweather.js workaround, because now I'm able to save my key without a problem from the interface. On the other hand, keys/api don't work, that's the problem.

**Comment by FreQRiDeR** [comment] 2024-06-29 16:29
I don't think the issue is exclusive to custom api keys as I am unable to fetch weather data from any source providers. Extension stopped working for me upon updating yesterday on Ubuntu 24.04.

**Comment by BooBerry** [comment] 2024-06-29 17:49
Same, even with my own custom API keys (that are valid) it still doesn't work and I'm also on Ubuntu 24.04.

**Comment by mrhoomanwastaken** [comment] 2024-06-29 21:18
> So I have a temporary solution to anyone stuck or can't get the API key to stick. You can replace the default key in the top of the getweather.js file (WeatherAPI is the second one) with your personal API key, then log out and in or otherwise reload your gnome session.
> 
> (You could possibly just manually add it into the second field of the custom-keys array in the schemas/*.xml file as well) *untested

this fix seemed to work for me. is the error with having too many users happening because it is near the end of the month and the default api keys have hit their limit?

**Comment by Thorazin** [comment] 2024-06-29 22:45
A suggestion, but the developer of thyis extension may want to email the weather api people and make sure he or she is accessing their API correctly. 

Here is why I say that. All the time I have been using my own API key, and even with the workaround in place,, Weather api . com still says I have not made a single api call. That's a bit strange don't you think?

**Comment by Thorazin** [comment] 2024-06-29 22:46
> > So I have a temporary solution to anyone stuck or can't get the API key to stick. You can replace the default key in the top of the getweather.js file (WeatherAPI is the second one) with your personal API key, then log out and in or otherwise reload your gnome session.
> > (You could possibly just manually add it into the second field of the custom-keys array in the schemas/*.xml file as well) *untested
> 
> this fix seemed to work for me. is the error with having too many users happening because it is near the end of the month and the default api keys have hit their limit?


That would make sense if it wasnt also not working for those of us with our own custom api key.

**Comment by washran** [comment] 2024-06-29 23:42
Wow, generic api keys aren't working. Put my api-key in the Default Keys section. Logged out and back in. Can confirm this works. I noticed almost all the people in this issue have problems with generic api-keys. Hope this gets fixed soon.

**Comment by Thorazin** [comment] 2024-06-29 23:49
> Wow, generic api keys aren't working. Put my api-key in the Default Keys section. Logged out and back in. Can confirm this works. I noticed almost all the people in this issue have problems with generic api-keys. Hope this gets fixed soon.


uhm, what? Lots of people here, me included, are using our own custom api keys and it is not working unless we use the workaround.

**Comment by TheRealWolfick** [comment] 2024-06-29 23:52
> A suggestion, but the developer of thyis extension may want to email the weather api people and make sure he or she is accessing their API correctly.
> 
> Here is why I say that. All the time I have been using my own API key, and even with the workaround in place,, Weather api . com still says I have not made a single api call. That's a bit strange don't you think?

I suspect that rather than our own API keys not working, there was a period where the extension simply reverted back to the default keys. As for analytics, it can take some time before calls are registered in the graph (although the home page still says 0 calls), this can be seen on the graph from my usage. I moved to a custom API key last time, and you can see when it must have reverted to the default key

![image](https://github.com/penguin-teal/gnome-openweather/assets/128224725/5fcb5d6c-1c45-40c2-8c5b-46767900818a)

**Comment by Thorazin** [comment] 2024-06-29 23:54
> > A suggestion, but the developer of thyis extension may want to email the weather api people and make sure he or she is accessing their API correctly.
> > Here is why I say that. All the time I have been using my own API key, and even with the workaround in place,, Weather api . com still says I have not made a single api call. That's a bit strange don't you think?
> 
> I suspect that rather than our own API keys not working, there was a period where the extension simply reverted back to the default keys. As for analytics, it can take some time before calls are registered in the graph (although the home page still says 0 calls), this can be seen on the graph from my usage. I moved to a custom API key last time, and you can see when it must have reverted to the default key
> 
> ![image](https://private-user-images.githubusercontent.com/128224725/344436051-5fcb5d6c-1c45-40c2-8c5b-46767900818a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MDU1MDIsIm5iZiI6MTcxOTcwNTIwMiwicGF0aCI6Ii8xMjgyMjQ3MjUvMzQ0NDM2MDUxLTVmY2I1ZDZjLTFjNDUtNDBjMi04YzViLTQ2NzY3OTAwODE4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQyMzUzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDNhYWY2MmNkYWM3NTY4Mzk5MWZlMTZkY2M2MmMxNzQ1ZGU2ZGI0NThlZDM2OWE3Nzg3ZmI2MjA0ZDM0OTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.juE2LSRuL4cAJ0asjF-fnyLvcq-0_Faya5LXI1XU7gU)


Very interesting.  I know nothing about programming but WeatherAPI . com gives a LOT of useful information to set it up properly from my brief searching on their website.

**Comment by rakkhin** [comment] 2024-06-30 06:55
I believe I found the problem, I've opened a PR to fix it. So far works locally :)

**Comment by TheRealWolfick** [comment] 2024-06-30 07:04
> > Thanks for the solution!! I confirm normal functioning of the extension. In my case, I modified the line with `DEFAULT_KEYS` in the file _getweather.js_ for my **OpenWeather API key**. Here a patch:
> 
> Nice solution! Took the liberty to comment the other keys out, works fine:
> 
> ```shell
> export const DEFAULT_KEYS =
> [
> //   "b4d6a638dd4af5e668ccd8574fd90cec",
>      "<My OPENWEATHERMAP api-key>"
> //   "7a4baea97ef946c7864221259240804",
> //   "ES25QFD3CP93EZ9DMSJ72MAX7"
> ];
> ```

This only works because the openweather API key is the first one and not recommended. 

You should just copy the default key "b4d6a638dd4af5e668ccd8574fd90cec" into a commented line outside of the array (if you want to save it). The way you have done it, your extension may crash if you change the provider as the array has changed from a size of 3 to 1. If there is anything else in the code that tries to access position [1] or [2], it will throw an out of bounds error.

**Comment by TheRealWolfick** [comment] 2024-06-30 07:20
> > This only works because the openweather API key is the first one and not recommended.
> 
> Now I get why there are 3 keys. But why are openweather API keys not recommended? Best weather provider, I won't switch.

That is not what I meant. I mean it is not recommended to change the size of the array so you, or anyone else, shouldn't use this as a solution. For instance, if you were to try change the weather provider to WeatherAPI.com and the code tries to access the key at DEFAULT_KEYS[1], it will throw an ArrayIndexOutOfBoundsException.

I hold no suggestions or recommendations on what weather provider one should use. That is entirely up to the person.

**Comment by grizzlysmit** [comment] 2024-06-30 10:24
same for me 30 June 2024 just does not work getting really frustrated with this mate, I know plugin development is hard but I waited so long for 136 to move to 137

**Comment by Ticklezz** [comment] 2024-06-30 11:23
> same for me 30 June 2024 just does not work getting really frustrated with this mate, I know plugin development is hard but I waited so long for 136 to move to 137

Ok, calm down. They picked up a deprecated extension and brought it back to life. All for free. Did you pay them anything? If not just be patient. The other can be made to work with a bit of work. You could try that one. The og version.

**Comment by grizzlysmit** [comment] 2024-06-30 19:23
> > same for me 30 June 2024 just does not work getting really frustrated with this mate, I know plugin development is hard but I waited so long for 136 to move to 137
> 
> Ok, calm down. They picked up a deprecated extension and brought it back to life. All for free. Did you pay them anything? If not just be patient. The other can be made to work with a bit of work. You could try that one. The og version.

Ummm I think you need to calm down no-one is spitting vitriol at penguin teal we are all just a tad disappointed that's we finally got a new version and it didn't work, as for changing plugin I would rather not before all this went wrong this was a superior plugin and having expression my disappointment, I will now wait hopefully for the author to fix this bug, which I am still confident he/she will succeed in doing.

Till then please don't get over excited about a few people trying to tell the author the bad news that we have still another bug, wish I could help by more than by telling author the bad news, but whilst I have some plugin skill I know nothing of the weather side of it

**Closed** 2024-07-01 00:10 UTC
Labels: bug

**Comment by penguin-teal** [comment] 2024-07-01 00:15
Thanks @rakkhin for fixing this very quickly. Once Open-Meteo gets added as a provider the extension should be in a stable state — I've been so rushed fixing the past bugs that fixing them brings out more.

**Comment by penguin-teal** [comment] 2024-07-01 00:48
By the way reading all this discussion I'll explain what the issue was because I can see why this was really confusing if you don't know the way it was programmed.

The keys are stored in a list like:

1. OpenWeatherMap
2. WeatherAPI.com
3. Visual Crossing

If any of them are "empty," it is replaced with the default key. Now WeatherAPI.com is no. 2, so it asked for the key but the bug is instead of grabbing no. 2 it grabbed no. 1. It saw nothing was in no. 1 and tried to use the OpenWeatherMap key for WeatherAPI.com.

**Comment by Ticklezz** [comment] 2024-07-01 01:01
> > > same for me 30 June 2024 just does not work getting really frustrated with this mate, I know plugin development is hard but I waited so long for 136 to move to 137
> > 
> > 
> > Ok, calm down. They picked up a deprecated extension and brought it back to life. All for free. Did you pay them anything? If not just be patient. The other can be made to work with a bit of work. You could try that one. The og version.
> 
> Ummm I think you need to calm down no-one is spitting vitriol at penguin teal we are all just a tad disappointed that's we finally got a new version and it didn't work, as for changing plugin, I would rather not before all this went wrong, this was a superior plugin and having expressed my disappointment, I will now wait hopefully for the author to fix this bug, which I am still confident he/she will succeed in doing.
> 
> Till then please don't get over excited about a few people trying to tell the author the bad news that we have still another bug, wish I could help by more than by telling author the bad news, but whilst I have some plugin skill I know nothing of the weather side of it

No you are being disrespectful for no reason. End of story. Telling him you are so frustrated but you waited so long. Did you pay them for their time? You seem to fail how you came off. We are here and you are the only who comes off like you paid money. So, next time just think about how you come off.

**Comment by Ticklezz** [comment] 2024-07-01 02:44
> By the way reading all this discussion I'll explain what the issue was because I can see why this was really confusing if you don't know the way it was programmed.
> 
> The keys are stored in a list like:
> 
>     1. OpenWeatherMap
> 
>     2. WeatherAPI.com
> 
>     3. Visual Crossing
> 
> 
> If any of them are "empty," it is replaced with the default key. Now WeatherAPI.com is no. 2, so it asked for the key but the bug is instead of grabbing no. 2 it grabbed no. 1. It saw nothing was in no. 1 and tried to use the OpenWeatherMap key for WeatherAPI.com.
> 
> Now only the code for querying the API was bugged which is why it saved fine in the settings menu and the GUI looked visibly fine.

Thank you for breathing life into this!!!
