### ISSUE TITLE
Unable to insert API key

### ISSUE THREAD

**Issue by kurtericmiller** [penguin-teal/gnome-openweather#43] opened 2024-06-14 17:01 UTC
## Description

Entry field in settings doesn't accept API key

## System

Ubuntu 24.04
## Settings

```json
Go to extension settings > "About" > "Copy Settings JSON" and paste here.
```
{"app-version":"136","git-version":"136.r1.g8d02397","gnome-version":"46.0","user-locale":"en","appid":"<KEY>","locs":"[(1, '', 1, '')]","my-loc-prov":"'geoclue'","weatherapidotcom-key":"<KEY>"}

**Comment by Artim96** [comment] 2024-06-14 17:06
Can confirm that. I have an API key for OpenWeatherMap, you can enter it, but it is forgotten upon closing the settings dialog.

Debian Testing with Gnome 46.2

**Comment by kurtericmiller** [comment] 2024-06-14 17:17
My workaround was to edit  ~/.local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/getweather.js and replace DEFAULT_KEYS with my key.

**Comment by creeper82** [comment] 2024-06-14 18:52
I have the same issue, but the @kurtericmiller 's workaround worked. I guess it's fine for now

**Comment by penguin-teal** [comment] 2024-06-14 20:25
Duplicate of #41 which has been fixed for the next release.

**Closed** 2024-06-14 20:26 UTC
Labels: bug, duplicate
