### ISSUE TITLE
Settings doesn't remember Custom API key for OpenWeatherMap

### ISSUE THREAD

**Issue by djandiek** [penguin-teal/gnome-openweather#42] opened 2024-06-14 00:33 UTC
## Description

Settings doesn't remember Custom API key for OpenWeatherMap

## System

Ubuntu 24.04

## Settings

```json
{"app-version":"136","git-version":"136.r1.g8d02397","gnome-version":"46.0","user-locale":"en","appid":"<KEY>","weather-provider":"'openweathermap'","has-run":"true","locs":"[(1, '', 1, '')]","my-loc-prov":"'ipinfoio'","weatherapidotcom-key":"<KEY>"}
```
![settings](https://github.com/penguin-teal/gnome-openweather/assets/4229472/e3ddef00-7fd5-4bff-aee5-a1ae9773ac3e)

**Comment by HiImJake** [comment] 2024-06-14 02:06
I'm having the same issue, cannot update with a personal API for OpenWeatherMap, was working fine prior to the update.
 `{"app-version":"136","git-version":"136.r1.g8d02397","gnome-version":"46.0","user-locale":"en","unit":"'fahrenheit'","appid":"<KEY>","actual-city":"0","prefs-default-width":"824","weather-provider":"'openweathermap'","sun-in-panel-first":"true","has-run":"true","days-forecast":"3","prefs-default-height":"600","delay-ext-init":"15","locs":"[(0, '<NAME>', 0, '<PLACE>')]","show-sunsetrise-in-panel":"false","last-init-error":"'(2024/05/12) TypeError: settings.set_value is not a function'","my-loc-prov":"'ipinfoio'","weatherapidotcom-key":"<KEY>","position-index":"1","pressure-unit":"'inHg'","position-in-panel":"'center'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}`

**Comment by wiggmpk** [comment] 2024-06-14 17:13
Confirming the same

{"app-version":"136","git-version":"136.r1.g8d02397","gnome-version":"45.5","user-locale":"en","unit":"'fahrenheit'","appid":"<KEY>","actual-city":"0","weather-provider":"'openweathermap'","sun-in-panel-first":"true","has-run":"true","days-forecast":"5","decimal-places":"1","locs":"[(0, '<NAME>', 0, '<PLACE>')]","expand-forecast":"false","show-sunsetrise-in-panel":"true","last-init-error":"'(2024/05/12) TypeError: settings.set_value is not a function'","my-loc-prov":"'geoclue'","weatherapidotcom-key":"<KEY>","position-index":"15","geolocation-provider":"'openstreetmaps'","wind-direction":"true","pressure-unit":"'psi'","menu-alignment":"59.239130434782602","position-in-panel":"'left'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}

**Comment by creeper82** [comment] 2024-06-14 18:25
Same

**Comment by penguin-teal** [comment] 2024-06-14 20:26
Duplicate of #41 which has been fixed for the next release.

**Closed by penguin-teal** 2024-06-14 20:26 UTC
Labels: bug, duplicate
