### ISSUE TITLE
Not able to receive weather reports from either api

### ISSUE THREAD

**Issue by Thorazin** [penguin-teal/gnome-openweather#35] opened 2024-05-18 18:28 UTC
## Description
Currently, neither OpenWeather or WeatherAPI are gathering weather data for the extension. Both are spamming my notifications with messages about too many users.

Describe the bug.
As stated above neither weather API functions and both spam my notifications with alerts  ~once every 2 seconds with a message about having too many users.

## System
?

Which Linux distro are you using?
Ubuntu 24.04

## Settings
Default, mostly.

```json
Go to extension settings > "About" > "Copy Settings JSON" and paste here.
```
{"app-version":"135","git-version":"135.r0.ge994aeb","gnome-version":"46.0","user-locale":"en","unit":"'fahrenheit'","appid":"<KEY>","actual-city":"1","weather-provider":"'weatherapicom'","has-run":"true","refresh-interval-current":"600","decimal-places":"1","locs":"[(1, '', 1, ''), (0, '<NAME>', 0, '<PLACE>')]","weatherapidotcom-key":"<KEY>","pressure-unit":"'inHg'","position-in-panel":"'center'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}

**Comment by moorepants** [comment] 2024-05-18 18:55
Same here. The notifications just caused my gnome shell to crash and log me out.

**Comment by Beast-Viper** [comment] 2024-05-18 19:12
Also same here. Had to disable the extension for my shell to be usable again.

**Comment by penguin-teal** [comment] 2024-05-18 19:41
Duplicate of #32.

**Closed** 2024-05-18 19:41 UTC
Labels: bug, duplicate

**Comment by Neo-29** [comment] 2024-06-28 20:47
This bug is coming back
Too Many requests

**Comment by penguin-teal** [comment] 2024-06-28 20:54
@Neo-29  Yeah I'll have to get Open-Meteo up and running soon — at least it isn't spamming this time.

**Comment by FreQRiDeR** [comment] 2024-06-29 16:31
Same issue (too many user requests) on 24.04 (Ubuntu) since updating yesterday.

**Comment by Beast-Viper** [comment] 2024-06-29 16:33
Please try using personal api key from openweather

Sent from Proton Mail Android

-------- Original Message --------
