### ISSUE TITLE
OpenWeather Refined Too Many Requests

### ISSUE THREAD

**Issue by ghost** [penguin-teal/gnome-openweather#82] opened 2024-09-28 15:38 UTC
## Description

OpenWeather Refined throws an error stating "OpenWeather Refined Has Too Many Requests. Provider [provider] has too many users. Try switching weather providers in settings." This happens with every provider defined in the extension.

![Screenshot from 2024-09-28 10-31-42](https://github.com/user-attachments/assets/9d66f9c4-0cb7-4a2a-a87c-a4817b566d0c)

## System

Distro: Fedora Linux 40 (Workstation Edition) x86_64
Kernel: Linux 6.10.10-200.fc40.x86_64
DE: GNOME 46.5

## Settings

```
{"app-version":"139","git-version":"138.r1.g2406098","gnome-version":"46.5","user-locale":"en","unit":"'fahrenheit'","custom-keys":["","",""],"appid":"<REDACTED>","actual-city":"0","weather-provider":"'default'","has-run":"true","days-forecast":"5","locs":[{},{}],"owm-api-translate":"false","weatherapidotcom-key":"<REDACTED>","wind-direction":"true","geolocation-appid-mapquest":"<REDACTED>","pressure-unit":"'inHg'","menu-alignment":"53.977272727272727","position-in-panel":"'center'","wind-speed-unit":"'mph'","show-comment-in-panel":"true"}
```

**Comment by penguin-teal** [comment] 2024-10-02 15:01
Duplicate of #32.
Also see #78 and [this comment](https://github.com/penguin-teal/gnome-openweather/issues/78#issuecomment-2369437018).

**Closed as completed by penguin-teal** 2024-10-02 15:01 UTC
Labels: duplicate, invalid
