### ISSUE TITLE
can't set API key, value is set to empty

### ISSUE THREAD

**Issue by netphantm** [penguin-teal/gnome-openweather#47] opened 2024-06-16 12:54 UTC
## Description

Personal API Key field conains a "!" and 'forgets' API key if I paste one there. after re-opening the settings dialog, this field is empty again.

## System

Ubuntu 24.10

## Settings

```json
{"app-version":"136","git-version":"136.r1.g8d02397","gnome-version":"46.0","user-locale":"en","appid":"<KEY>","actual-city":"0","weather-provider":"'openweathermap'","has-run":"true","days-forecast":"3","delay-ext-init":"10","locs":"[(0, '<NAME>', 0, '<PLACE>'), (0, '<NAME>', 0, '<PLACE>')]","expand-forecast":"true","weatherapidotcom-key":"<KEY>"}
```
![image](https://github.com/penguin-teal/gnome-openweather/assets/4569298/e83f0974-b913-4917-9883-636baf710946)

from the log
```
2024-06-16T14:53:33.680834+02:00 zoidberg gjs[107065]: JS ERROR: Error: GSettings key keys not found in schema org.gnome.shell.extensions.openweatherrefined#012_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:779:23#012createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:729:30#012settingsSetKeys@file:///home/hugo/.local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/locs.js:381:12#012GeneralPage/<@file:///home/hugo/.local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/preferences/generalPage.js:470:22#012_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by mlmilliman** [comment] 2024-06-16 16:55
The same goes for geolocation data. The extension doesn't use the keys for geolocation either.

**Comment by Austaras** [comment] 2024-06-17 05:08
Duplicate of #41, but maybe a new release should be made soon as possible?

**Comment by netphantm** [comment] 2024-06-17 06:50
yeah, I didn't find that one, cos it's closed..

**Comment by businessBoris** [comment] 2024-06-21 13:15
Got an Open Weather API key can't adde the key as it says it's invalid. I've copy-pasted it from the Open Weather email and it's not accepted - there's no way to actually test the key validity - no button to click etc - it just shows a triangle with a pling (!) in. I've waited the several hours to let them make it valid.
I guess that's probably why it isn't saved anywhere.
Either way, that feature doesn't work at all.

**Comment by lev741** [comment] 2024-06-25 10:27
Same on Fedora 40 Workstation. 
I tried use dconf to set key but no luck.

**Comment by pnearing** [comment] 2024-06-25 14:32
> Duplicate of #41, but maybe a new release should be made soon as possible?

In the comment thread there, about 2 weeks ago, penguin-teal, the owner of the repo said a release will be soon.  Is there any update on this?

**Comment by jhpratt** [comment] 2024-06-25 23:50
Based on #51 (which presumably fixes this issue), this worked for me:

```sh
gsettings --schemadir ~/.local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/schemas set org.gnome.shell.extensions.openweatherrefined custom-keys "['', '<key>', '', '']"
```

**Comment by lamyergeier** [comment] 2024-06-26 04:52
Facing it on Fedora 40 Gnome

**Comment by djandiek** [comment] 2024-06-28 01:21
Just tried @jhpratt solution (using my API key) for [openweathermap.org](https://openweathermap.org/) and it works.

**Comment by penguin-teal** [comment] 2024-06-28 15:08
Duplicate of #41.

**Closed by penguin-teal** 2024-06-28 15:08 UTC
Labels: bug
